# Makefile for btnode application

# define btnut root directory
top_srcdir = ../../../btnut

# include standard compiler and linker flags
include $(top_srcdir)/Makedefs

# set proj name
PROJ = routing

# define your sources
SRCS =  $(PROJ).c

# only btnode3 platform
PLATFORMS=btnode3

# include rules how to build the targets
# include Makefile.extra
include $(top_srcdir)/Makerules

#type 'make btnode2' or 'make btnode3' to compile and
#'make burn btnode2' or 'make burn btnode3' to upload the program code