# Makefile for btnode application

# define btnut root directory
top_srcdir = ../../btnut

# include standard compiler and linker flags
include $(top_srcdir)/Makedefs


# set proj name
PROJ = sniffer

# btnode3 only
PLATFORMS=btnode3 unix

# define your sources
SRCS =  $(PROJ).c

# include rules how to build the targets
# include Makefile.extra
include $(top_srcdir)/Makerules

#type 'make btnode2' or 'make btnode3' to compile and
#'make burn btnode2' or 'make burn btnode3' to upload the program code

